<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="evaluator.arith.ArithPostFixEvaluatorTest" tests="9" skipped="0" failures="2" errors="0" timestamp="2017-06-24T21:40:41" hostname="pv16mbpr23" time="0.051">
  <properties/>
  <testcase name="testEvaluateNegate" classname="evaluator.arith.ArithPostFixEvaluatorTest" time="0.022"/>
  <testcase name="testEvaluateSimple" classname="evaluator.arith.ArithPostFixEvaluatorTest" time="0.002"/>
  <testcase name="testEvaluateSub" classname="evaluator.arith.ArithPostFixEvaluatorTest" time="0.006"/>
  <testcase name="testEvaluate" classname="evaluator.arith.ArithPostFixEvaluatorTest" time="0.005">
    <failure message="java.lang.AssertionError: expected:&lt;21&gt; but was:&lt;7&gt;" type="java.lang.AssertionError">java.lang.AssertionError: expected:&lt;21&gt; but was:&lt;7&gt;
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:118)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at evaluator.arith.ArithPostFixEvaluatorTest.testEvaluate(ArithPostFixEvaluatorTest.java:77)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:745)
</failure>
  </testcase>
  <testcase name="testEvaluateMult" classname="evaluator.arith.ArithPostFixEvaluatorTest" time="0.007"/>
  <testcase name="testEvaluatePlus" classname="evaluator.arith.ArithPostFixEvaluatorTest" time="0.002">
    <failure message="java.lang.AssertionError: expected:&lt;3&gt; but was:&lt;-1&gt;" type="java.lang.AssertionError">java.lang.AssertionError: expected:&lt;3&gt; but was:&lt;-1&gt;
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:118)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at evaluator.arith.ArithPostFixEvaluatorTest.testEvaluatePlus(ArithPostFixEvaluatorTest.java:29)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:745)
</failure>
  </testcase>
  <testcase name="testInvalidExpression2" classname="evaluator.arith.ArithPostFixEvaluatorTest" time="0.003"/>
  <testcase name="testInvalidExpression3" classname="evaluator.arith.ArithPostFixEvaluatorTest" time="0.001"/>
  <testcase name="testInvalidExpression" classname="evaluator.arith.ArithPostFixEvaluatorTest" time="0.001"/>
  <system-out><![CDATA[]]></system-out>
  <system-err><![CDATA[]]></system-err>
</testsuite>
