<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="language.arith.PlusOperatorTest" tests="6" skipped="0" failures="1" errors="0" timestamp="2017-06-24T21:40:41" hostname="pv16mbpr23" time="0.007">
  <properties/>
  <testcase name="testIllegalArgumentException" classname="language.arith.PlusOperatorTest" time="0.001"/>
  <testcase name="testIllegalStateException" classname="language.arith.PlusOperatorTest" time="0.0"/>
  <testcase name="testPerformOperation" classname="language.arith.PlusOperatorTest" time="0.001">
    <failure message="java.lang.AssertionError: Operator applied to 5 and 7 should produce 11. expected:&lt;12&gt; but was:&lt;-2&gt;" type="java.lang.AssertionError">java.lang.AssertionError: Operator applied to 5 and 7 should produce 11. expected:&lt;12&gt; but was:&lt;-2&gt;
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at language.arith.PlusOperatorTest.testPerformOperation(PlusOperatorTest.java:32)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:745)
</failure>
  </testcase>
  <testcase name="testGetNumberOfArguments" classname="language.arith.PlusOperatorTest" time="0.002"/>
  <testcase name="testNullArgumentException" classname="language.arith.PlusOperatorTest" time="0.001"/>
  <testcase name="testIllegalStateExceptionPerform" classname="language.arith.PlusOperatorTest" time="0.001"/>
  <system-out><![CDATA[]]></system-out>
  <system-err><![CDATA[]]></system-err>
</testsuite>
